### ISSUE TITLE
AttributeError: 'Parameter' object has no attribute 'grad_batch'

### ISSUE THREAD

**Issue by Nikki-Gu** [chehx/DGDR#2]
您好，在运行DRGen算法时会出现如下错误，请问这是什么原因呢？

Traceback (most recent call last):
  File "main.py", line 35, in <module>
    loss_dict_iter = algorithm.update(minibatch)   
  File "/home/user2/Medical/SD_Medical/code/DGDR/algorithms.py", line 420, in update
    loss_dict_iter = self.algorithm.update(minibatch)
  File "/home/user2/Medical/SD_Medical/code/DGDR/algorithms.py", line 306, in update
    penalty = self.compute_fishr_penalty(all_logits, all_y, len_minibatches)
  File "/home/user2/Medical/SD_Medical/code/DGDR/algorithms.py", line 326, in compute_fishr_penalty
    dict_grads = self._get_grads(all_logits, all_y)
  File "/home/user2/Medical/SD_Medical/code/DGDR/algorithms.py", line 341, in _get_grads
    for name, weights in self.classifier.named_parameters()
  File "/home/user2/Medical/SD_Medical/code/DGDR/algorithms.py", line 341, in <listcomp>
    for name, weights in self.classifier.named_parameters()
AttributeError: 'Parameter' object has no attribute 'grad_batch'

**Comment by Nikki-Gu** [comment]
目前代码里面支持的算法只有algorithms.py中所列出的前三个是吗？其他的都还未完全实现是吗:D
ALGORITHMS = [
    'ERM',
    'GDRNet',
    'GREEN',
    'CABNet',
    'MixupNet',
    'MixStyleNet',
    'Fishr',
    'DRGen'
    ]

**Comment by Chelsea-abab** [comment]
您好，ALGORITHMS里列出的算法我们都已经实现在algorithms.py文件中，您可以查看一下。然后对于您提到的错误AttributeError: 'Parameter' object has no attribute 'grad_batch'，可能是由于您安装的backpack-for-pytorch库版本不对，请问您运行环境的pytorch和backpack-for-pytorch分别是什么版本呢？

**Comment by Chelsea-abab** [comment]
您可以在[这里](https://github.com/chehx/DGDR/blob/main/requirements.txt)看一下运行所需要的库的版本。

**Comment by Nikki-Gu** [comment]
您好，我看到algorithms.py中关于CABNet的代码只有如下部分，请问是否是具体实现的代码还未上传呢？
class CABNet(ERM):
    def __init__(self, num_classes, cfg):
        super(CABNet, self).__init__(num_classes, cfg)

**Comment by Nikki-Gu** [comment]
谢谢您提出的关于版本不对的建议，我的显卡是CUDA12.1，支持配置的torch环境为
torch==1.13.1+cu117  
torchvision==0.14.1+cu117
对应需要使用
backpack-for-pytorch==1.5.2
所以出现了上述问题，再次感谢您的回复。

**Comment by Nikki-Gu** [comment]
很抱歉再次打扰您，我切换到CUDA版本较低的显卡成功运行了DRGen的代码，但是在最后验证和保存模型时遇到了如下问题，不知道您是否遇到过相同问题？

> Traceback (most recent call last):
  File "main.py", line 55, in <module>
    _, test_auc = algorithm.validate(val_loader, test_loader, writer)
  File "/home/user7/AIGC/DGDR/algorithms.py", line 455, in validate
    self.swad_algorithm = self.swad.get_final_model()
  File "/home/user7/AIGC/DGDR/modeling/nets.py", line 641, in get_final_model
    self.smooth_Q.popleft()
IndexError: pop from an empty deque

**Comment by Chelsea-abab** [comment]
> 您好，我看到algorithms.py中关于CABNet的代码只有如下部分，请问是否是具体实现的代码还未上传呢？ class CABNet(ERM): def **init**(self, num_classes, cfg): super(CABNet, self).**init**(num_classes, cfg)

您好，关于这个问题，cabnet的训练部分是与他继承的class ERM完全相同的，所以这里只用super()函数来完成了。cabnet的model部分是在另一个文件modeling.nets里实现的，所以cabnet应该是可以正常运行的。

**Comment by Chelsea-abab** [comment]
> 很抱歉再次打扰您，我切换到CUDA版本较低的显卡成功运行了DRGen的代码，但是在最后验证和保存模型时遇到了如下问题，不知道您是否遇到过相同问题？
> 
> > Traceback (most recent call last):
> > File "main.py", line 55, in 
> > _, test_auc = algorithm.validate(val_loader, test_loader, writer)
> > File "/home/user7/AIGC/DGDR/algorithms.py", line 455, in validate
> > self.swad_algorithm = self.swad.get_final_model()
> > File "/home/user7/AIGC/DGDR/modeling/nets.py", line 641, in get_final_model
> > self.smooth_Q.popleft()
> > IndexError: pop from an empty deque

我们并没有遇到这个问题，看起来像是drgen代码的swad部分没有成功运行。请问您在运行drgen的代码时有正常的输出吗，我们默认是每隔10个epoch来validate的，这些结果正常吗？

**Comment by Nikki-Gu** [comment]
> > 很抱歉再次打扰您，我切换到CUDA版本较低的显卡成功运行了DRGen的代码，但是在最后验证和保存模型时遇到了如下问题，不知道您是否遇到过相同问题？
> > > Traceback (most recent call last):
> > > File "main.py", line 55, in
> > > _, test_auc = algorithm.validate(val_loader, test_loader, writer)
> > > File "/home/user7/AIGC/DGDR/algorithms.py", line 455, in validate
> > > self.swad_algorithm = self.swad.get_final_model()
> > > File "/home/user7/AIGC/DGDR/modeling/nets.py", line 641, in get_final_model
> > > self.smooth_Q.popleft()
> > > IndexError: pop from an empty deque
> 
> 我们并没有遇到这个问题，看起来像是drgen代码的swad部分没有成功运行。请问您在运行drgen的代码时有正常的输出吗，我们默认是每隔10个epoch来validate的，这些结果正常吗？

这部分结果是正常输出的，只是在最后会出现上述bug，不清楚这是否会影响最终结果？

**Comment by Chelsea-abab** [comment]
> > > 很抱歉再次打扰您，我切换到CUDA版本较低的显卡成功运行了DRGen的代码，但是在最后验证和保存模型时遇到了如下问题，不知道您是否遇到过相同问题？
> > > > Traceback (most recent call last):
> > > > File "main.py", line 55, in
> > > > _, test_auc = algorithm.validate(val_loader, test_loader, writer)
> > > > File "/home/user7/AIGC/DGDR/algorithms.py", line 455, in validate
> > > > self.swad_algorithm = self.swad.get_final_model()
> > > > File "/home/user7/AIGC/DGDR/modeling/nets.py", line 641, in get_final_model
> > > > self.smooth_Q.popleft()
> > > > IndexError: pop from an empty deque
> > 
> > 
> > 我们并没有遇到这个问题，看起来像是drgen代码的swad部分没有成功运行。请问您在运行drgen的代码时有正常的输出吗，我们默认是每隔10个epoch来validate的，这些结果正常吗？
> 
> 这部分结果是正常输出的，只是在最后会出现上述bug，不清楚这是否会影响最终结果？

应该是不会的，DRGen算法是基于Fishr算法再加上swad的算法来进行的，我们过程中输出的结果也都是DRGen的结果了并不是fishr的，所以应该不会影响最终结果。你可以看一下是哪里导致的最后保存出现问题。
