### ISSUE TITLE
The images you used are different from the original images in APTOS dataset

### ISSUE THREAD

**Issue by Van-NguyenPham** [chehx/DGDR#4]
I take a look at your preprocessed APTOS dataset: 

https://hkustconnect-my.sharepoint.com/personal/hche_connect_ust_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhche%5Fconnect%5Fust%5Fhk%2FDocuments%2FResearch%2FGDRBench%2FGDRBench%5FAllowedShare%2Ezip&parent=%2Fpersonal%2Fhche%5Fconnect%5Fust%5Fhk%2FDocuments%2FResearch%2FGDRBench&ga=1

and found that many images are different from the original dataset: 

https://www.kaggle.com/competitions/aptos2019-blindness-detection/data

there are so many different images, here are 3 of them in the training set:
- 2db0cd3e30da.png
- 2dc647e00ad3.png
- 2cfe8703f265.png

**Comment by Chelsea-abab** [comment]
I have checked the images you mentioned in both our preprocessed APTOS dataset and official website, and found that they are exactly the same. The former is preprocessed from the latter by some means explained in [here](https://github.com/chehx/DGDR/tree/main/GDRBench#process). You can double check it. I hope this could help you!

![screenshot](https://github.com/chehx/DGDR/assets/75232629/03bb6a49-f03b-4f9f-8d5c-42f26af81e16)

**Comment by Van-NguyenPham** [comment]
I don't know what the problem is but the images I downloaded from your onedrive look different:
![Screenshot from 2024-05-14 09-54-58](https://github.com/chehx/DGDR/assets/43635525/330ee4f7-c3ed-4a57-88d0-0dd3e31881b7)

**Comment by Chelsea-abab** [comment]
Sorry for late reply! I have checked again and found that some errors seem to happen during the compression. I will update a new download link soon. Much thanks for your information!

**Comment by Chelsea-abab** [comment]
[link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/ychengbj_connect_ust_hk/EquCDy8pIARCuuX_yYYC4OcBj2C81FeK1_sNxYScPiBVWA?e=jp4zO1)
This is a link for you to download the correct GDRBench(part). I hope this can help you!

**Comment by yuu-Wang** [comment]
> [link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/ychengbj_connect_ust_hk/EquCDy8pIARCuuX_yYYC4OcBj2C81FeK1_sNxYScPiBVWA?e=jp4zO1) This is a link for you to download the correct GDRBench(part). I hope this can help you!

不好意思我想问一下，您的这个链接数据集也下载不了了呢？原链接好像也没有权限了
